language: clojure
lein: lein2
before_install:
  - ./bin/ci/start_neo4j_server.sh
script: lein2 all test
jdk:
  - openjdk6
  - openjdk7
  # until Leiningen 2 Preview 5 HTTPS connection issues are resolved
  # - oraclejdk7
